# Generated by Django 4.2.11 on 2024-04-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=200)),
                ('rezyser', models.CharField(max_length=100)),
                ('rok_produkcji', models.IntegerField()),
                ('ocena', models.FloatField(max_length=2)),
                ('gatunki', models.CharField(max_length=200)),
            ],
        ),
    ]
