# Generated by Django 4.2.11 on 2024-05-20 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MojaStrona', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='gatunki',
        ),
        migrations.RemoveField(
            model_name='film',
            name='ocena',
        ),
        migrations.RemoveField(
            model_name='film',
            name='rezyser',
        ),
        migrations.RemoveField(
            model_name='film',
            name='rok_produkcji',
        ),
        migrations.AddField(
            model_name='film',
            name='imdb_points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='opis',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='film',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filmy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='film',
            name='premiera',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='rok',
            field=models.PositiveSmallIntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='film',
            name='tytul',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recenzja', models.TextField(blank=True, default='')),
                ('gwiazdki', models.PositiveSmallIntegerField(default=5)),
                ('film', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MojaStrona.film')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oceny', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czas_trwania', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gatunek', models.PositiveSmallIntegerField(blank=True, choices=[(2, 'Komedia'), (1, 'Horror'), (0, 'Inne'), (4, 'Dramat'), (3, 'Sci-fi')], null=True)),
                ('rezyser', models.CharField(blank=True, max_length=50, null=True)),
                ('filmy', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MojaStrona.film')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='einfo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aktor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=32)),
                ('nazwisko', models.CharField(max_length=32)),
                ('filmy', models.ManyToManyField(blank=True, to='MojaStrona.film')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aktorzy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
