# Generated by Django 4.2.11 on 2024-05-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MojaStrona', '0002_remove_film_gatunki_remove_film_ocena_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(3, 'Sci-fi'), (1, 'Horror'), (4, 'Dramat'), (0, 'Inne'), (2, 'Komedia')], null=True),
        ),
    ]
