# Generated by Django 4.2.11 on 2024-05-20 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MojaStrona', '0006_alter_extrainfo_gatunek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Inne'), (1, 'Horror'), (4, 'Dramat'), (3, 'Sci-fi'), (2, 'Komedia')], null=True),
        ),
    ]
